variables:
  SPARK_VERSION: "3.1.2"
  HADOOP_VERSION: "3.2"
  SPARK_DIST: "spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION"
  SPARK_GIT_REF: "v$SPARK_VERSION"
  SPARK_HOME: "/tmp/$SPARK_DIST"

stages:
  - lint
  - build_and_test
  - spellcheck
  - deploy

linting:
  image: rocker/tidyverse
  stage: lint
  when: on_success
  script:
    - R -e 'install.packages(c("lintr", "styler"))'
    - dev/lint.sh

building_and_testing:
  image: rocker/tidyverse
  stage: build_and_test
  when: on_success
  script:
    - sudo apt update && sudo apt install -y openjdk-11-jdk-headless
    - wget https://dlcdn.apache.org/spark/spark-$SPARK_VERSION/$SPARK_DIST.tgz
    - tar xf $SPARK_DIST.tgz && mv $SPARK_DIST /tmp && rm $SPARK_DIST.tgz
    - R -e 'remotes::install_git("https://github.com/apache/spark.git", subdir="R/pkg", ref=Sys.getenv("SPARK_GIT_REF"))'
    - R -e 'remotes::install_deps(dependencies = TRUE)'
    - Rscript -e 'install.packages(c("covr", "DT"))'
    - Rscript -e 'remotes::install_git("https://github.com/zero323/pkgdown.git@gitlab-icon")'
    - Rscript -e 'remotes::install_git("https://github.com/amirmasoudabdol/preferably.git")'
    - dev/build-and-test.sh
    - dev/build-docs.sh
  artifacts:
    expire_in: 45 mins
    paths:
      - docs

spellchecking:
  image: vlajos/misspell-fixer
  stage: spellcheck
  allow_failure: true
  script:
    - misspell-fixer -v README.md R tests

pages:
  image: rocker/tidyverse
  stage: deploy
  dependencies:
    - building_and_testing
  script:
    - mv docs public
  artifacts:
    paths:
      - public
    expire_in: 45 mins
  only:
    - main
